# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78ec362f0ce866b54b0cd579b065b4a28766702e651328d227764415044057ac52ae4f44c66ce15785f418cec5438f36c6337170d01fb54d75c887f4a641a1b0

test:
  secret_key_base: 71d0456b634921d373665e853dea61069f909f4f08d67181e20210815c4cd9c9c6c9da5db6155decf253cb63de61d3087e7e14af48803770bdbca813514f29cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
